apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: mycluster-dal10-b3c.4x16
    devEnvApprovers:
    - todo
    environmentGitOwner: narendra-ch-os
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: openshift
    registry: ghcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "mycluster-dal10-b3-863626-560f6f5e338640cda943b314d2536ac3-0000.us-south.containers.appdomain.cloud"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
